/datum/unit_test/underwater_airlocks/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent, get_step(run_loc_floor_bottom_left, NORTH))
	for(var/door_type in list(/obj/machinery/door/airlock/highsecurity/underwater, /obj/machinery/door/airlock/highsecurity/underwater/multi_tile))
		var/obj/machinery/door/airlock/highsecurity/underwater/door = allocate(door_type, run_loc_floor_bottom_left)
		door.autoclose = FALSE
		if(door.dir != SOUTH)
			return Fail("Underwater doors must spawn in their default horizontal orientation.")
		if(door.max_integrity != 600)
			return Fail("Underwater doors must have vault integrity.")
		if(door.atom_integrity != 600)
			return Fail("Underwater doors must start at full integrity.")
		if(door.explosion_block != 2)
			return Fail("Underwater doors must have vault blast resistance.")
		var/obj/structure/door_assembly/assembly_type = door.assemblytype
		if(initial(assembly_type.airlock_type) != door_type)
			return Fail("Rebuilding must preserve the door type.")
		if(initial(assembly_type.dir) != SOUTH)
			return Fail("Assemblies must use the same default orientation as their doors.")
		var/list/states = icon_states(door.icon)
		for(var/state in list("closed", "open", "fill_closed", "fill_open", "opening", "closing", "fill_opening", "fill_closing", "wheel_locked", "wheel_unlocked", "wheel_locking", "wheel_unlocking", "lights_poweron", "lights_poweron_open", "lights_bolts", "lights_denied", "lights_opening", "lights_closing"))
			if(!(state in states))
				return Fail("Missing underwater airlock icon state: [state].")

		door.machine_stat |= NOPOWER
		door.set_main_outage(60 SECONDS)
		door.set_backup_outage(60 SECONDS)
		door.click_alt(user)
		if(!door.handwheel_locked)
			return Fail("The handwheel must lock without power.")
		door.bolt()
		door.unbolt()
		if(!door.handwheel_locked)
			return Fail("Powered bolts must not unlock the mechanical handwheel.")
		for(var/force_type in list(DEFAULT_DOOR_CHECKS, FORCING_DOOR_CHECKS, BYPASS_DOOR_CHECKS))
			if(door.open(force_type))
				return Fail("An engaged handwheel must prevent forced opening.")
		door.click_alt(user)
		if(door.handwheel_locked)
			return Fail("The handwheel must unlock without power.")
		door.handwheel_turning = TRUE
		if(door.open(BYPASS_DOOR_CHECKS))
			return Fail("The door must stay closed while the handwheel turns.")
		door.handwheel_turning = FALSE
		if(!door.open(BYPASS_DOOR_CHECKS))
			return Fail("An unlocked door must still support normal crowbar forcing.")
		if(door.density || door.opacity)
			return Fail("An open underwater door must let mobs and sight pass.")
		if(door.multi_tile)
			if(door.filler.density || door.filler.opacity)
				return Fail("The second tile must open too.")
		door.click_alt(user)
		if(door.handwheel_locked)
			return Fail("The handwheel cannot lock an open door.")
		if(!door.close(BYPASS_DOOR_CHECKS))
			return Fail("An unlocked door must close normally.")
		if(door.multi_tile)
			if(!door.filler.density || !door.filler.opacity)
				return Fail("The second tile must close too.")
			for(var/direction in GLOB.cardinals)
				door.setDir(direction)
				var/horizontal = (direction in list(NORTH, SOUTH))
				if(door.dir != (horizontal ? SOUTH : EAST))
					return Fail("Two-tile doors must have only horizontal and vertical orientations.")
				if(door.bound_width != (horizontal ? 64 : 32))
					return Fail("Two-tile width does not match direction.")
				if(door.bound_height != (horizontal ? 32 : 64))
					return Fail("Two-tile height does not match direction.")
				if(get_turf(door.filler) != get_step(door, horizontal ? EAST : NORTH))
					return Fail("Filler must follow rotated two-tile doors.")
		else
			for(var/direction in GLOB.cardinals)
				door.setDir(direction)
				if(door.dir != SOUTH)
					return Fail("One-tile doors must keep a single fixed orientation.")
		qdel(door)
